FROM qmcgaw/godevcontainer
RUN apk add curl
# RUN apk add bash
# RUN curl -O 'https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/install.sh'
# RUN git clone --depth 1 --branch master --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts.git /root/nerd-fonts
# WORKDIR /root/nerd-fonts
# RUN git sparse-checkout add patched-fonts/Go-Mono
# RUN chmod +x install.sh
# RUN ./install.sh Go-Mono
# WORKDIR /root
# RUN rm -rf /root/nerd-fonts
# RUN rm install.sh